pyweekly/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from issues.views import *

urlpatterns = patterns('',
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^issues/$', issues_list, name='issue_list'),
    url(r'^issues/(\d+)/', issue_articles_list),
    url(r'^weblog/', include('weblog.urls.entries')),
    url(r'^weblog/categories/', include('weblog.urls.categories')),

    url(r'^admin/', include(admin.site.urls)),
)

issues/models.py
# -*- coding: utf-8 -*-

import datetime
from markdown import markdown

from django.db import models


class Category(models.Model):
    title = models.CharField(u'类别名称', max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(u'类别简介', blank=True)
    ctime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title']
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.title


class Issue(models.Model):
    issue_num = models.IntegerField(u'期数', help_text=u'必须是正整数')
    title = models.CharField(u'本期名称', max_length=200)
    description = models.TextField(u'关于本期的简介')
    pub_date = models.DateTimeField(u'发布时间', default=datetime.datetime.now)

    def __unicode__(self):
        return self.title


class Article(models.Model):
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    HIDE_STATUS = 3
    STATUS_CHOICES = ((LIVE_STATUS, u'发布'),
                      (DRAFT_STATUS, u'草稿'),
                      (HIDE_STATUS, u'隐藏'),)
    title = models.CharField(u'标题', max_length=250)
    slug = models.SlugField(unique=True)
    excerpt = models.TextField(u'内容介绍', blank=True)
    source_link = models.URLField(u'来源链接')
    translation_link = models.URLField(u'中文翻译链接', blank=True)
    pub_date = models.DateTimeField(u'发布时间', default=datetime.datetime.now)
    view_num = models.IntegerField(default=1)

    excerpt_html = models.TextField(editable=False, blank=True)

    issue = models.ManyToManyField(Issue)
    category = models.ForeignKey(Category)
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS,
                                 help_text=u'只有文章为发布状态才会在页面显示')

    class Meta:
        ordering = ['-pub_date']

    def __unicode__(self):
        return self.title

    def save(self, force_insert=False, forse_update=False):
        if self.excerpt:
            self.excerpt_html = markdown(self.excerpt)
        super(Article, self).save(force_insert, forse_update)

weblog/models.py
# -*- coding: utf-8 -*-

import datetime
from markdown import markdown

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Category(models.Model):
    title = models.CharField(u'类别标题', max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    class Meta:
        ordering = ["title"]
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/weblog/categories/%s/" % self.slug


class LiveEntryManager(models.Manager):
    def get_queryset(self):
        return super(LiveEntryManager,
                     self).get_queryset().filter(status=self.model.LIVE_STATUS)


class Entry(models.Model):
    DRAFT_STATUS = 1
    LIVE_STATUS = 2
    HIDDEN_STATUS = 3
    STATUS_CHOICES = (
        (DRAFT_STATUS, "草稿"),
        (LIVE_STATUS, "发布"),
        (HIDDEN_STATUS, "隐藏")
    )
    # Core fields.
    title = models.CharField(max_length=200)
    excerpt = models.TextField(blank=True)
    content = models.TextField()
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    # Fields to store genereted HTML.
    excerpt_html = models.TextField(editable=False, blank=True)
    content_html = models.TextField(editable=False, blank=True)

    # Metadata.
    author = models.ForeignKey(User, related_name='authors')
    enable_comments = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(unique_for_date="pub_date")
    status = models.SmallIntegerField(choices=STATUS_CHOICES,
                                      default=LIVE_STATUS)

    # Categories.
    categories = models.ManyToManyField(Category, related_name='entries')

    # manager
    live = LiveEntryManager()
    objects = models.Manager()

    class Meta:
        ordering = ["-pub_date"]
        verbose_name_plural = "Entries"

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.content_html = markdown(self.content)
        if self.excerpt:
            self.excerpt_html = markdown(self.excerpt)
        super(Entry, self).save(*args, **kwargs)

    def get_absolute_url(self):
        """
        return like 'entries/2015/02/01/python-unittest/'
        """
        return reverse('entry_detail', args=[self.pub_date.strftime("%Y"),
                                             self.pub_date.strftime("%m"),
                                             self.pub_date.strftime("%d"),
                                             self.slug])
        #return "/weblog/%s/%s/" % (self.pub_date.strftime("%Y/%m/%d"),
        #                           self.slug)

issues/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Issue, Article
from weblog.models import Entry


def home(request):
    issues = Issue.objects.all()[:2]
    entries = Entry.live.all()[:5]
    return render(request, 'home.html', {'issues': issues,
                                         'entries': entries})

def issues_list(request):
    issues = Issue.objects.all()
    return render(request, 'issue_list.html', {'issues': issues})


def issue_articles_list(request, issue_num):
    issue = Issue.objects.get(issue_num=issue_num)
    if issue:
        articles = issue.article_set.all()
    else:
        print 'issue not found'
        articles = []
    return render(request, 'issue_article_list.html',
                  {'articles': articles, 'issue_num': issue_num})

weblog/views.py
from django.shortcuts import render
from django.views.generic.dates import (ArchiveIndexView, DateDetailView,
                                        YearArchiveView, MonthArchiveView,
                                        DayArchiveView)
from django.views.generic.list import ListView

from .models import Entry, Category


class CategoryListView(ListView):
    model = Category
    context_object_name = "categories"


def category_detail(request, slug):
    cat = Category.objects.get(slug=slug)
    entries = cat.entries.all()
    return render(request, 'entry_archive.html', {'entries': entries})


class EntryArchiveIndexView(ArchiveIndexView):
    queryset = Entry.live.all()
    date_field = "pub_date"
    context_object_name = "entries"
    template_name = 'entry_archive.html'


class EntryDateDetailView(DateDetailView):
    model = Entry
    context_object_name = "entry"
    date_field = "pub_date"
    month_format = "%m"   # default is %b
    template_name = 'entry_detail.html'


class EntryYearArchiveView(YearArchiveView):
    model = Entry
    make_object_list = True
    context_object_name = "entries"
    date_field = "pub_date"
    template_name = 'entry_archive.html'
    allow_future = True


class EntryMonthArchiveView(MonthArchiveView):
    model = Entry
    context_object_name = "entries"
    date_field = "pub_date"
    month_format = "%m"
    template_name = 'entry_archive.html'


class EntryDayArchiveView(DayArchiveView):
    model = Entry
    context_object_name = "entries"
    date_field = "pub_date"
    month_format = "%m"
    template_name = 'entry_detail.html'

weblog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>{% block title %}{% endblock %} T&P</title>
    <meta name="author" content="Teddy">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <!--[if lte IE 6]>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-ie6.min.css">
    <![endif]-->
    <!--[if lte IE 7]>
    <link rel="stylesheet" type="text/css" href="/static/css/ie.css">
    <![endif]-->
    <link rel='stylesheet' href='/static/css/all.css' />
    {% block head_css %}{% endblock %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="{% block bodyclass %}{% endblock %}">
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="/">Home</a></li>
          <li>  <a href="{% url 'issue_list' %}">期刊</a></li>
          <li><a href="{% url 'weblog_entry_archive' %}">博客</a></li>
        </ul>
        <h3 class="text-muted">Teddy & Pudding</h3>
      </div>

      <div class="row">
      {% block topList %}
        
      {% endblock %}
    </div>
    
      <div class="row">
          {% block content %}
          {% endblock %}
      </div>
      <div class="footer">
        <p>&copy; Company 2015</p>
      </div>
    </div><!-- container ends -->
    <script src="/static/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/static/js/all.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

weblog/templates/base_issues.html
{% extends "base.html" %}

{% block head_css %}
    <link href="/static/css/jumbotron-narrow.css" rel="stylesheet">
{% endblock %}

{% block title %}
    | 期刊
{% endblock %}

{% block bodyclass %}issues{% endblock %}

weblog/templates/base_tags.html
{% extends "coltrane/base.html" %}

{% block title %}
    |标签列表
{% endblock %}

{% block bodyclass %}
    tags
{% endblock %}

weblog/templates/base_weblog.html
{% extends 'base.html' %}

{% block title %}
   博客 |
{% endblock %}

{% block bodyclass %}weblog{% endblock %}

{% block sidebar %}
  
{% endblock %}

weblog/templates/entry_archive.html
{% extends "base_weblog.html" %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block content %}
{% for entry in entries %}
<h2>{{ entry.title }}</h2>
<p>发表于{{ entry.pub_date|date:"F j, Y"}}</p>
{% if entry.excerpt_html %}
{{ entry.excerpt_html|safe }}
{% else %}
{{ entry.body_html|slice:"50"|safe }}
{% endif %}
<p><a href="{{ entry.get_absolute_url }}">Read full entry</a></p>
{% endfor %}
{% endblock %}

{% block whatis %}
<p>这是最新博文列表，共{{ entries.count }}篇。</p>
{% endblock %}

weblog/templates/entry_archive_day.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Entries index By Day</title>
        
    </head>
    <body>
        <h1>Entries index By Day</h1>
        {% for entry in object_list %}
        <h2>{{ entry.title }}</h2>
        <p>Published on {{ entry.pub_date|date:"F j, Y"}}</p>
        {% if entry.excerpt_html %}
        {{ entry.excerpt_html|safe }}
        {% else %}
        {{ entry.body_html|slice:"50"|safe }}
        {% endif %}
        <p><a href="{{ entry.get_absolute_url }}">Read full entry</a></p>
        {% endfor %}
    </body>
</html>

weblog/templates/entry_archive_month.html
{% extends "coltrane/base_entries.html" %}

{% block title %}
{{ block.super }} | Entries in {{ month|date:"F, Y" }}
{% endblock %}

{% block content %}
{% for entry in object_list %}
<h2>{{ entry.title }}</h2>
<p>Published on {{ entry.pub_date|date:"F j, Y" }}</p>
{% if entry.excerpt_html %}
{{ entry.excerpt_html|safe }}
{% else %}
{{ entry.body_html|slice:"50"|safe }}
{% endif %}
<p><a href="{{ entry.get_absolute_url }}" >Read full entry...</a></p>
{% endfor %}
</ul>
{% endblock %}

{% block whatis %}
<p>{{ month|date:"F, Y" }}的博文列表</p>
{% endblock %}

weblog/templates/entry_archive_year.html
{% extends "coltrane/base_entries.html" %}

{% block title %}
{{ block.super }} | {{ year|date:"Y" }}
{% endblock %}

{% block content %}
<ul>
{% for month in date_list %}
<li>
    <a href="/weblog/{{ year|date:"Y" }}/{{ month|date:"b"|lower}}/">{{ month|date:"F" }}</a>
    <a href="{% url 'coltrane_entry_archive_month' year|date:"Y" month|date:"b" %}">{{ month|date:"F" }}</a>
</li>
{% endfor %}
</ul>
{% endblock %}

{% block whatis %}
<p>{{ year|date:"Y" }}的月份的列表</p>
{% endblock %}

weblog/templates/entry_detail.html
{% extends "base_weblog.html" %}

{% block title %}
{{ block.super }} | {{ entry.title }}
{% endblock %}

{% block content %}
<h2>{{ entry.title }}</h2>
{{ entry.content_html|safe }}
{% endblock %}

{% block whatis %}
<p>
    This is an entry posted to my blog on {{ object.pub_date|date:"F j, Y" }}.
</p>
{% if object.categories.count %}
<p>This entry is part of the categor{{ object.categories.count|pluralize:"y,ies" }}
    {% for category in object.categories.all %}
    <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
    {% if forloop.last %}{% else %}
    {% ifequal forloop.revcounter0 1 %}and {% else %}, {% endifequal %}
    {% endif %}
    {% endfor %}
</p>
{% else %}
<p>This entry isn't part of any categories.</p>
{% endif %}
{% if object.tags.count %}
<p>This entry has tags:
{% for tag in object.tags.all %}
<a href="{% url 'coltrane_tag_entry_list' tag.id %}">{{ tag.name }}</a>
{% if forloop.last %}
{% else %}
{% ifequal forloop.revcounter0 1 %}and {% else %},
{% endifequal %}
{% endif %}
{% endfor %}
</p>
{% endif %}
{% endblock %}

weblog/templates/entry_index.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Entries index</title>
        
    </head>
    <body>
        <h1>Entries index</h1>
        {% for entry in entry_list %}
        <h2>{{ entry.title }}</h2>
        <p>Published on {{ entry.pub_date|date:"F j, Y"}}</p>
        {% if entry.excerpt_html %}
        {{ entry.excerpt_html|safe }}
        {% else %}
        {{ entry.body_html|slice:"50"|safe }}
        {% endif %}
        <p><a href="{{ entry.get_absolute_url }}">Read full entry</a></p>
        {% endfor %}
    </body>
</html>

weblog/templates/home.html
{% extends 'base_issues.html' %}

{% block title %}
首页 |
{% endblock %}

{% block bodyclass %}home{% endblock %}

{% block topList %}

<div id="issueOne" class="col-lg-5">
<h2>期刊1</h2>
</div>
<div  class="col-lg-5 col-lg-offset-2">
  <div id="issueTwo" class="well">
    <h2>期刊2</h2>
    <p>
        导致原因 通常是因为指定的 URL 在 Django 的 URL
        导致原因 通常是因为指定的 URL 在 Django 的 URL
        导致原因 通常是因为指定的 URL 在 Django 的 URL
        处理系统中有”记录”(即己配置), 但是映射到 view 上时出错, 通常是找不到
        view .  
    </p>
  </div>
</div>
{% endblock %}


{% block content %}

<hr>
<div id="entryList">
{% for entry in entries %}
<h2>{{ entry.title }}</h2>
<p>发表于{{ entry.pub_date|date:"F j, Y"}}</p>
{% if entry.excerpt_html %}
{{ entry.excerpt_html|safe }}
{% else %}
{{ entry.body_html|slice:"50"|safe }}
{% endif %}
<p><a href="{{ entry.get_absolute_url }}">Read full entry</a></p>
{% endfor %}
</div>
    
{% endblock %}

weblog/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Narrow Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <h3 class="text-muted">Project name</h3>
      </div>

      <div class="jumbotron">
        <h1>Jumbotron heading</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

      <div class="footer">
        <p>&copy; Company 2014</p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

weblog/templates/issue_article_list.html
{% extends "base_issues.html" %}

{% block title %}第{{ issue_num }}期{{ block.super }}{% endblock %}

{% block content %}

{% for entry in articles %}
<h2><a href="{{ entry.source_link }}" target="_blank">{{ entry.title }}</a></h2>
<p>发布于：{{ entry.pub_date|date:"F j, Y"}}</p>
{{ entry.excerpt_html|safe }}
<p>来源：<a href="{{ entry.source_link }}">{{ entry.source_link }}</a></p>
<p>中文翻译：<a href="{{ entry.translation_link }}">{{ entry.translation_link }}</a></p>
{% endfor %}

{% endblock %}

weblog/templates/issue_list.html
{% extends "base_issues.html" %}

{% block title %}期刊列表 {{ block.super }}{% endblock %}

{% block content %}
<h4>Python、Django有关的网络博文选编</h4>
<div>
  <ul>
    {% for issue in issues %}
    <li>
      <a href="/issues/{{ issue.issue_num }}">{{ issue.title }}</a>
      <span class="pull-right">{{ issue.pub_date|date:"F j, Y" }}</span>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}